embedding_dir: "CMU_config1_z_d80_bm_10i" # 'training_output_17_21_07_03_2024_1'
wandb_job_name: 'z0_bm_d80_10e'
rank_metrics: True
model_type: "linear"
epochs: 5120
loss_type: "L1"
metric: "PCC"
task: 0
