embedding_dir: "CMU_config1_z_d60_bm_10i" # 'training_output_23_54_05_03_2024'
wandb_job_name: 'z0_bm_d60_10e'
rank_metrics: True
model_type: "linear"
epochs: 5120
loss_type: "L1"
metric: "PCC"
task: 0
