embedding_dir: 'training_output_05_55_08_03_2024_1'
wandb_job_name: 'mt_z_60e_60i'
wandb_name: 'TCGA_Embedding_eval'
rank_metrics: True
model_type: "linear"
epochs: 10001
loss_type: "BCE"
metric: "F1"
task: -1
lr: 1e-4
