embedding_dir: "TCGA_d60_80i" # 'training_output_01_06_08_03_2024_8'
wandb_job_name: 'mt_60e_80i'
rank_metrics: True
model_type: "linear"
epochs: 10001
loss_type: "BCE"
metric: "F1"
task: -1
lr: 1e-4
